### ISSUE TITLE
Assignment 7: Step 3 - determine the necessary AWS IAM permissions to generate ECS cluster via Travis

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/hacku-devops-2017#4]
I first tried Assignment 7 with an AWS IAM account (defined as ./bin/secrets.sh:AWS_ACCESS_KEY) that is granted the AmazonEC2FullAccess permission.

Running the command in Step 3 (./bin/standup-ec2-cluster.sh) with this AWS access account results in this error message:

`
DOCKER_WEB_IMAGE: django-web
ERRO[0010] Failed to Create Cluster                      cluster=assign7-hacko error="AccessDeniedException: User: arn:aws:iam::720781686731:user/Mike is not authorized to perform: ecs:CreateCluster on resource: *\n\tstatus code: 400, request id: eba9b4ce-ef48-11e6-b6ec-01f5bae2b4e4"
ERRO[0010] Error executing 'up': AccessDeniedException: User: arn:aws:iam::720781686731:user/Mike is not authorized to perform: ecs:CreateCluster on resource: *
	status code: 400, request id: eba9b4ce-ef48-11e6-b6ec-01f5bae2b4e4 
`

Dan was showing how to create an IAM account and he highlighted the ECS* permissions, so I added AmazonEC2ContainerServiceFullAccess permission.

With EC2* and EC2ContainerService* permissions, the Step 3 script then resulted in this:

`
DOCKER_WEB_IMAGE: django-web
INFO[0007] Created cluster                               cluster=assign7-hacko
INFO[0008] Waiting for your cluster resources to be created... 
INFO[0008] Cloudformation stack status                   stackStatus="CREATE_IN_PROGRESS"
ERRO[0038] Failure event                                 reason="API: iam:CreateRole User: arn:aws:iam::720781686731:user/Mike is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::720781686731:role/assign7-hacko-EcsInstancePolicy-VK5X1C5PHL1G" resourceType="AWS::IAM::Role"
ERRO[0038] Error executing 'up': Cloudformation failure waiting for 'CREATE_COMPLETE'. State is 'ROLLBACK_IN_PROGRESS' 
`

I'll continue to investigate so that we can document this for the class (and/or next season's DevOps class).  If anyone else happens to find this and knows the answer, please comment! :)

**Comment by MikeTheCanuck** [comment]
By adding IAMFullAccess permission to my AWS account, Step 3 finally completed without errors.

For purposes of class, granting these three permissions to the account we use is certainly a working combination:
- AmazonEC2FullAccess
- AmazonEC2ContainerServiceFullAccess
- IAMFullAccess

Hopefully for purposes of enabling the Hack Oregon projects, we can find some less-powerful set of permissions to assign to the account configured for use by TravisCI when building the Django and/or Postgres container images.

**Comment by pdxdiver** [comment]
Don't really think we want teams creating new ECS clusters.  I don't view this pipeline, the one for creating infrastructure, as one that is done infrequently and done outside the act of a code deploy. The act of creating and deploying a container, on the other hand, will be a frequent occurrence and we do need to narrow down on the IAM roles required to perform this function. Just my humble opinion.

**Comment by MikeTheCanuck** [comment]
Now that you mention it, that seems pretty overboard.

Let's work out a procedure for what the DevOps squad members will do for each project team (one time) and what we expect the project teams to be able to routinely do on their own, in terms of this API layer deployment.

I'd also like to tackle a procedure description for the data replication and update sequence that we'll enable on behalf of project developers. That should be fun to work through ;)

**Comment by pdxdiver** [comment]
See the readme:

https://github.com/hackoregon/backend-service-pattern/blob/master/README.md
